spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  datasource:
    url: jdbc:mysql://localhost:3306/aihealthcaredb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rexyoon
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  spring:
    liquibase:
      change-log: classpath:/db/changelog/db.changelog-master.yaml


  autoconfigure:
    exclude: org.springframework.ai.vectorstore.elasticsearch.autoconfigure.ElasticsearchVectorStoreAutoConfiguration


    jpa:
      hibernate:
        ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            format_sql: true
          show-sql: true
          database-platform: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.hivernate.SQL: debug
    org.hibernate.type.descroptor.sql: trace